import type { Metadata } from "next";
import { Geist, Geist_Mono, Jaro, Jockey_One, McLaren } from "next/font/google";
import "@fontsource/martian-mono";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jaro = Jaro({
  variable: "--font-jaro",
  subsets: ["latin"],
});

const jockeyOne = Jockey_One({
  variable: "--font-jockey-one",
  subsets: ["latin"],
  weight: "400",
});

const mclaren = McLaren({
  variable: "--font-mclaren",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ scrollBehavior: 'smooth' }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jaro.variable} ${jockeyOne.variable} ${mclaren.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
